version: '3'
services:
    redis:
        image: "redis:alpine"
        ports: 
            - "6379:6379"
    nodejs:
        build: ./nodejs
        ports: 
            - "3000:3000"
        volumes:
            - "./nodejs:/usr/src/app"
        depends_on:
            - redis
        links:
            - redis
    python:
        build: ./python
        ports: 
            - "4000:4000"
        volumes:
            - "./python:/usr/src/app"
        depends_on:
            - redis
        links:
            - redis
    php-fpm:
        build: ./php-fpm
        ports: 
            - "5000:5000"
        volumes:
            - "./php-fpm:/usr/src/app"
        depends_on:
            - redis
        links:
            - redis
