version: '3'
services:
    redis:
        image: "redis:alpine"
        ports: 
            - "6379:6379"
    nodejs:
        build: ./nodejs
        ports: 
            - "3000:3000"
        volumes:
            - "./nodejs:/usr/src/app"
        depends_on:
            - redis
        links:
            - redis